variables:
- name: nugetBuildName
  value: '1.5.$(date:yy)$(DayOfYear)$(rev:.r)'
- name: DotnetVersion
  value: '6.0.x'

trigger:
  batch: true
  branches:
    include:
      - master
      - develop

pr:
- master
- develop

jobs:
- job: LinuxJob
  pool:
    name: Apption Pool
  workspace:
    clean: all

  steps:
  - script: |
      echo source branch name is $(Build.SourceBranchName)
      echo dotnet version is $(DotnetVersion)
    displayName: 'Run a one-line script'
